# MediaDB — the single build entrypoint.
#
# There was none. The README documented one command, CI ran four in an order
# recorded only in a YAML comment, and two published endpoints were regenerated by
# nothing at all (findings PIPE-02, STALE-01). Every build step now lives here, and
# .github/workflows/build-api.yml calls these targets, so the workflow and the docs
# cannot drift apart again.
#
# The corpus in data/media is a FROZEN SNAPSHOT: its generators are dead and its raw
# inputs are gone (PIPE-01). Corrections are therefore transform stages under
# tools/stages/, composed by `make stages`, and promoted deliberately by
# `make promote`. No target here ever writes data/media as a side effect.
#
# The chain's INPUT ships with the repository. It used to be an untracked archive on
# one machine (../media_curate_backups/data_media_20260906.tar.zst), so `make stages`
# and `make stages-sample` both failed from a fresh clone — PIPE-01 recreated one
# level up, in the very targets that exist to fix it. The pre-remediation corpus is
# now committed at data/_baseline/ (3.7 MB, expands to 13,515 records) and expanded
# by `make baseline`. `make reproduce` runs the whole chain from it and compares the
# result to the corpus that ships.
#
#   make help          list the targets
#   make all           check -> stages -> test -> derived   (never promotes)
#   make reproduce     baseline -> stages -> compare against data/media
#   make preflight     everything CI checks, before you push

PY      ?= python3
REPO    := $(shell pwd)
MEDIA   ?= $(REPO)/data/media
REBUILD := $(REPO)/data/_rebuild
STAGED  := $(REBUILD)/media
SAMPLE  := $(REBUILD)/sample/media
BASELINE:= $(REBUILD)/baseline/media
BACKUPS ?= $(REPO)/../media_curate_backups
STAMP   := $(shell date +%Y%m%d-%H%M%S)

.PHONY: help all check baseline sample stages-sample stages test test-fast test-strict \
        derived coverage coverage-index index api cluster stats presence web manifest \
        verify reproduce preflight ci-paths ci-paths-check manifest-check \
        refs-verify release-assets size \
        promote fetch fixtures clean-rebuild

help:
	@echo "MediaDB build targets"
	@echo "  check         registry <-> filesystem consistency for tools/stages/"
	@echo "  baseline      expand + verify the committed chain input (data/_baseline)"
	@echo "  sample        build the deterministic 165-record sample corpus"
	@echo "  stages-sample run the stage chain over the sample (fast; checks idempotence)"
	@echo "  stages        run the stage chain over all media -> data/_rebuild/media"
	@echo "  reproduce     stages, then compare the result to the shipped data/media"
	@echo "  test          pytest: schema, invariants, defect ledger, harness, tools"
	@echo "  test-strict   same, but xfail-ledger entries must PASS (CI gate, later)"
	@echo "  derived       rebuild index/stats/coverage/api/cluster/presence/web + MANIFEST"
	@echo "  web           rebuild data/web/* (the browser payload) only"
	@echo "  manifest      rebuild data/MANIFEST.json only"
	@echo "  verify        rebuild derived into a temp dir and report differences"
	@echo "  refs-verify   data/refs.json and data/media resolve each other"
	@echo "  release-assets  build dist/api/{media.sqlite.gz,media.jsonl.part*.gz}"
	@echo "  size          what the published site weighs vs the 1 GiB Pages limit"
	@echo "  preflight     every check CI runs, in CI's order — run before pushing"
	@echo "  ci-paths      regenerate the workflow trigger list from this Makefile"
	@echo "  fetch         re-acquire the public upstream sources (network)"
	@echo "  fixtures      vendor frozen test fixtures from the source cache"
	@echo "  promote       back up data/media, then promote data/_rebuild/media over it"
	@echo "  all           check -> stages -> test -> derived"

all: check stages test derived

# ---------------------------------------------------------------- stage chain

check:
	$(PY) tools/stages/run_stages.py --check

# The chain's input, shipped in the repository. Idempotent: a tree that already
# matches the archive's digest is left alone, so `make stages` does not re-expand
# 443 MB on every run.
baseline:
	$(PY) tools/baseline.py --out "$(BASELINE)"

# The sample is drawn from the chain INPUT, not from data/media. Sampling data/media
# fed the stages their own output: stage 10 counted 906 non-BiGG fallbacks against
# 913 unmapped components and `make stages-sample` failed on a clean checkout.
sample: baseline
	$(PY) tools/stages/make_sample.py --from "$(BASELINE)"

stages-sample: sample
	$(PY) tools/stages/run_stages.py --sample

stages: check baseline
	$(PY) tools/stages/run_stages.py --in "$(BASELINE)"

# The reproduction claim, executed rather than asserted: run every stage from the
# committed input and compare the result to the corpus that ships. The chain stamps
# provenance.transforms[].date with the day it runs, so the date the shipped corpus
# carries is fed back in — otherwise the only difference between a reproduction and
# the published corpus would be today's date, and a check that has to ignore a field
# is weaker than one that does not.
reproduce: check baseline
	MEDIADB_STAMP_DATE=$$($(PY) tools/compare_corpora.py --stamp-date "$(MEDIA)") \
	  $(PY) tools/stages/run_stages.py --in "$(BASELINE)"
	$(PY) tools/compare_corpora.py "$(STAGED)" "$(MEDIA)" \
	  --json "$(REBUILD)/reproduce_report.json"

# ---------------------------------------------------------------------- tests

test:
	$(PY) -m pytest tests -q -rX

test-fast:
	$(PY) -m pytest tests -q -rX --limit 400

# Once the defect ledger in tests/test_defects.py is empty, this becomes the CI gate.
test-strict:
	$(PY) -m pytest tests -q --runxfail

# ------------------------------------------------------- derived artifacts
# Order is load-bearing and is proven by data flow, not by convention:
#   the stage chain writes the per-medium `coverage` and `coverage_source` blocks
#     that build_coverage_index and build_index read (stage 39 owns them now, which
#     is why `coverage` is not in this list — see the note on that target);
#   build_index writes data/index.json that build_api_exports reads;
#   build_api_exports writes the parquet that build_cluster_data reads.
# build_media_stats and build_presence_matrix were in no workflow at all, which is
# why two published endpoints shipped 1,128 media stale (STALE-01), and
# data/coverage.json lost its generator entirely when stage 39 took authorship —
# tools/build_coverage_index.py projects it from the corpus instead.

derived: refs-verify coverage-index index api cluster stats presence web manifest

# data/refs.json holds each cross-reference block and each prose note ONCE, and the
# 665,582 components refer to them by key (stage 60_dedupe_references). Every builder
# below joins that table, so a corpus and a table that disagree would produce blank
# cross-reference columns in the parquet and a blank cell on the site, with no error
# anywhere. This runs FIRST and refuses.
refs-verify:
	$(PY) tools/verify_reference_tables.py

# `coverage` is NO LONGER part of `derived`, and that is a correctness fix, not a
# convenience. Stage 39_recompute_coverage owns the coverage numbers once the chain
# has run, and tools/enrich_coverage.py refuses (correctly) to run over a corpus
# carrying its stamp. Leaving it in the chain of derived targets meant `make derived`
# aborted on its first step against a promoted corpus. The legacy enricher stays
# available for a corpus the chain has NOT processed, which is the only case where
# it is the authority.
coverage-index:
	$(PY) tools/build_coverage_index.py

coverage:
	$(PY) tools/enrich_coverage.py

index:
	$(PY) build_index.py

api:
	$(PY) tools/build_api_exports.py

cluster:
	$(PY) tools/build_cluster_data.py

stats:
	$(PY) tools/build_media_stats.py

# The browser payload. It is built LAST of the data steps and BEFORE the manifest,
# because it is projected straight from data/media and the manifest hashes it.
# The same projection runs inside the chain as tools/stages/52_web_payload.py, so a
# correction that makes the browser's honesty numbers unbuildable fails `make stages`
# rather than surfacing on the deployed site.
web:
	$(PY) tools/build_web_payload.py

presence:
	$(PY) tools/build_presence_matrix.py

manifest:
	$(PY) tools/build_manifest.py

verify:
	$(PY) tools/verify_derived.py

# ------------------------------------------------------------ release assets
# GitHub Pages publishes this repository's ROOT and refuses a published site over
# 1 GiB. media.sqlite.gz and the two media.jsonl shards are a second and third
# encoding of data/media — which is itself published, and must stay published,
# because assets/media.js fetches data/media/<id>.json at runtime — and they
# measured 24.1 + 83.9 + 64.8 = 172.8 MiB. They are built here, into an untracked
# dist/, and distributed as assets on the `data-v1` release instead.
#
# THE RELEASE DOES NOT EXIST YET. Nothing is served from
# github.com/omidard/Media/releases/download/data-v1 — the tag has never been
# created — so data/api/manifest.json declares bulk_download.status = "planned",
# every document tells a reader to build the files here instead, and pymediadb
# reads that status rather than fetching a 404. This target is the supported way
# to get them today, and it needs no network:
#
#   make release-assets      # -> dist/api/{media.sqlite.gz,media.jsonl.part01.gz,
#                            #             manifest.json,RELEASE_NOTES.md}
#
# To publish them once the branch is pushed (so the tag has a target) and gh is
# authenticated — the note is generated by the build, not typed:
#
#   gh release create data-v1 dist/api/*.gz --repo omidard/Media \
#     --title 'MediaDB bulk exports (data-v1)' --notes-file dist/api/RELEASE_NOTES.md
#   curl -sIL -o /dev/null -w '%{http_code}\n' \
#     https://github.com/omidard/Media/releases/download/data-v1/media.sqlite.gz
#
# then flip RELEASE_STATUS to "published" in tools/build_api_exports.py, run
# `make derived`, and commit data/api/manifest.json. `make derived` does NOT
# rebuild the assets themselves; run this target whenever the corpus changes.
release-assets:
	$(PY) tools/build_api_exports.py --bulk

# What the published site weighs, measured the way it is published: the bytes of
# every TRACKED file, because GitHub Pages serves the repository root.
size:
	$(PY) tools/report_site_size.py

manifest-check:
	$(PY) tools/build_manifest.py --check
	$(PY) tools/build_manifest.py --check-tree

# The workflow's `paths:` trigger list is generated from this Makefile and from
# data/MANIFEST.json, because maintaining it by hand is how it came to name a script
# `make derived` no longer runs while omitting two it does.
ci-paths:
	$(PY) tools/build_ci_paths.py

ci-paths-check:
	$(PY) tools/build_ci_paths.py --check

# Everything CI checks, in CI's order. Run this before pushing: a red check here is
# a red check there, and the artifacts CI commits are the ones this verifies.
#
# `derived` before `manifest-check` is the point of the gate, not an accident: the
# manifest must describe the artifacts a rebuild produces AND the bytes git holds,
# which is the defect CI would otherwise have shipped (a manifest describing a
# payload it did not commit). That order used to make preflight permanently red,
# because the payload builders stamped a wall-clock built_utc into the files the
# manifest hashes, so a freshly rebuilt artifact could never match the committed
# one. The stamp is now written only when the payload itself changes
# (tools/web_payload.write_payload_file, tools/build_manifest.carry_stamps_forward),
# so a rebuild of unchanged data writes no bytes, this passes from a clean tree, and
# it still fails the moment data/web is genuinely stale or unstaged
# (tests/test_ci_reproducibility.py seeds exactly that and requires the failure).
preflight: check ci-paths-check stages-sample test derived manifest-check
	@echo "preflight OK — registry, trigger paths, sample chain, tests, derived"
	@echo "artifacts and the manifest/committed-tree agreement all pass."

# ------------------------------------------------------------------- sources

fetch:
	$(PY) tools/fetch_sources.py --all

fixtures:
	$(PY) tools/fetch_sources.py --fixtures

# ------------------------------------------------------------------- promote
# The only step that touches data/media. It refuses to run without a chain result,
# backs the corpus up first, and prints what changed.

promote:
	@test -d "$(STAGED)" || { echo "no corrected corpus at $(STAGED) — run 'make stages' first"; exit 1; }
	@mkdir -p "$(BACKUPS)"
	@echo "backing up data/media -> $(BACKUPS)/data_media_$(STAMP).tar.zst"
	@tar -cf - data/media | zstd -q -3 -o "$(BACKUPS)/data_media_$(STAMP).tar.zst"
	@$(PY) tools/promote_corpus.py --from "$(STAGED)" --to "$(MEDIA)"
	@# The reference table is part of the corpus, not a derived artifact: it holds the
	@# cross-references and notes the records no longer carry inline. Promoting one
	@# without the other leaves the site with keys nothing resolves, so they move
	@# together, and `make refs-verify` proves it afterwards. Stage 60 writes it
	@# beside the corpus it belongs to; the symlink is resolved so this works for a
	@# full chain run and a single-stage run alike.
	@refs="$$(cd "$$(dirname "$$(readlink -f "$(STAGED)")")" && pwd)/refs.json"; \
	if [ -f "$$refs" ]; then \
		cp "$$refs" "$(REPO)/data/refs.json"; \
		echo "promoted data/refs.json ($$refs) alongside the corpus"; \
	else \
		echo "NOTE: no refs.json beside $(STAGED) — data/refs.json left as it is."; \
		echo "      Run 'make refs-verify' before 'make derived'."; \
	fi
	@echo "promoted. Now run: make refs-verify && make derived && make test"

clean-rebuild:
	@echo "removing regenerated staging trees under data/_rebuild (never source data)"
	rm -rf "$(REBUILD)/stages" "$(REBUILD)/sample_run"
