# MediaDB — the single build entrypoint.
#
# There was none. The README documented one command, CI ran four in an order
# recorded only in a YAML comment, and two published endpoints were regenerated by
# nothing at all (findings PIPE-02, STALE-01). Every build step now lives here, and
# .github/workflows/build-api.yml calls these targets, so the workflow and the docs
# cannot drift apart again.
#
# The corpus in data/media is a FROZEN SNAPSHOT: its generators are dead and its raw
# inputs are gone (PIPE-01). Corrections are therefore transform stages under
# tools/stages/, composed by `make stages`, and promoted deliberately by
# `make promote`. No target here ever writes data/media as a side effect.
#
#   make help          list the targets
#   make all           check -> stages -> test -> derived   (never promotes)

PY      ?= python3
REPO    := $(shell pwd)
MEDIA   ?= $(REPO)/data/media
REBUILD := $(REPO)/data/_rebuild
STAGED  := $(REBUILD)/media
SAMPLE  := $(REBUILD)/sample/media
BACKUPS ?= $(REPO)/../media_curate_backups
STAMP   := $(shell date +%Y%m%d-%H%M%S)

.PHONY: help all check sample stages-sample stages test test-fast test-strict \
        derived index api cluster stats presence manifest verify promote fetch \
        fixtures clean-rebuild

help:
	@echo "MediaDB build targets"
	@echo "  check         registry <-> filesystem consistency for tools/stages/"
	@echo "  sample        build the deterministic 165-record sample corpus"
	@echo "  stages-sample run the stage chain over the sample (fast; checks idempotence)"
	@echo "  stages        run the stage chain over all media -> data/_rebuild/media"
	@echo "  test          pytest: schema, invariants, defect ledger, harness, tools"
	@echo "  test-strict   same, but xfail-ledger entries must PASS (CI gate, later)"
	@echo "  derived       rebuild index/stats/coverage/api/cluster/presence + MANIFEST"
	@echo "  manifest      rebuild data/MANIFEST.json only"
	@echo "  verify        rebuild derived into a temp dir and report differences"
	@echo "  fetch         re-acquire the public upstream sources (network)"
	@echo "  fixtures      vendor frozen test fixtures from the source cache"
	@echo "  promote       back up data/media, then promote data/_rebuild/media over it"
	@echo "  all           check -> stages -> test -> derived"

all: check stages test derived

# ---------------------------------------------------------------- stage chain

check:
	$(PY) tools/stages/run_stages.py --check

sample:
	$(PY) tools/stages/make_sample.py

stages-sample: sample
	$(PY) tools/stages/run_stages.py --sample

stages: check
	$(PY) tools/stages/run_stages.py

# ---------------------------------------------------------------------- tests

test:
	$(PY) -m pytest tests -q -rX

test-fast:
	$(PY) -m pytest tests -q -rX --limit 400

# Once the defect ledger in tests/test_defects.py is empty, this becomes the CI gate.
test-strict:
	$(PY) -m pytest tests -q --runxfail

# ------------------------------------------------------- derived artifacts
# Order is load-bearing and is proven by data flow, not by convention:
#   enrich_coverage writes the per-medium `coverage` block that build_index reads;
#   build_index writes data/index.json that build_api_exports reads;
#   build_api_exports writes the parquet that build_cluster_data reads.
# build_media_stats and build_presence_matrix were in no workflow at all, which is
# why two published endpoints shipped 1,128 media stale (STALE-01).

derived: coverage index api cluster stats presence manifest

coverage:
	$(PY) tools/enrich_coverage.py

index:
	$(PY) build_index.py

api:
	$(PY) tools/build_api_exports.py

cluster:
	$(PY) tools/build_cluster_data.py

stats:
	$(PY) tools/build_media_stats.py

presence:
	$(PY) tools/build_presence_matrix.py

manifest:
	$(PY) tools/build_manifest.py

verify:
	$(PY) tools/verify_derived.py

# ------------------------------------------------------------------- sources

fetch:
	$(PY) tools/fetch_sources.py --all

fixtures:
	$(PY) tools/fetch_sources.py --fixtures

# ------------------------------------------------------------------- promote
# The only step that touches data/media. It refuses to run without a chain result,
# backs the corpus up first, and prints what changed.

promote:
	@test -d "$(STAGED)" || { echo "no corrected corpus at $(STAGED) — run 'make stages' first"; exit 1; }
	@mkdir -p "$(BACKUPS)"
	@echo "backing up data/media -> $(BACKUPS)/data_media_$(STAMP).tar.zst"
	@tar -cf - data/media | zstd -q -3 -o "$(BACKUPS)/data_media_$(STAMP).tar.zst"
	@$(PY) tools/promote_corpus.py --from "$(STAGED)" --to "$(MEDIA)"
	@echo "promoted. Now run: make derived && make test"

clean-rebuild:
	@echo "removing regenerated staging trees under data/_rebuild (never source data)"
	rm -rf "$(REBUILD)/stages" "$(REBUILD)/sample_run"
