"""Every link on a published page must open something a browser can display.

THE DEFECT THIS FILE EXISTS FOR
-------------------------------
The footers linked `href="NOTICE"` and the methods page linked `href="LICENSE"`.
Both files are extensionless, so a static host has nothing to type them by and
labels them `application/octet-stream`, which no browser renders inline: clicking
either one downloaded an unnamed file into the reader's downloads folder instead
of showing the terms. Confirmed on the deployment (both HTTP 200,
`content-type: application/octet-stream`) and reproduced by the local server
here, which types these paths identically. The sibling `.md` links were served as
`text/markdown` and rendered, so the fault is specific to the two extensionless
files rather than to static hosting.

NOTICE is the only place the seven upstream sources' individual terms are
enumerated, and this library aggregates 13,515 media from them, so a reader
checking what they are allowed to do got a download and no text.

The generated `.txt` copies are asserted byte-identical to the extensionless
originals, because two hand-maintained copies of a licence would drift, and
`LICENSE` has to stay in place for the host's own licence detection.
"""
import functools
import http.server
import os
import re
import socket
import threading
import urllib.request

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = ["index.html", "families.html", "compare.html", "patterns.html",
         "methods.html"]
LEGAL_PAIRS = [("LICENSE", "LICENSE.txt"), ("NOTICE", "NOTICE.txt")]


@pytest.fixture(scope="module")
def server():
    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=REPO)
    handler.log_message = lambda *a, **k: None                    # noqa: ARG005
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        port = s.getsockname()[1]
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", port), handler)
    httpd.RequestHandlerClass.log_message = lambda *a, **k: None  # noqa: ARG005
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    yield "http://127.0.0.1:%d" % port
    httpd.shutdown()


def _local_hrefs(page_name):
    """Relative, same-directory link targets on one page, minus in-page anchors."""
    with open(os.path.join(REPO, page_name), encoding="utf-8") as fh:
        html = fh.read()
    out = set()
    for href in re.findall(r'<a\b[^>]*\bhref="([^"]+)"', html):
        if href.startswith(("#", "http://", "https://", "mailto:", "data:")):
            continue
        out.add(href.split("#", 1)[0])
    return sorted(h for h in out if h)


@pytest.mark.parametrize("page_name", PAGES)
def test_every_link_on_a_page_opens_something_a_browser_can_show(server, page_name):
    if not os.path.exists(os.path.join(REPO, page_name)):
        pytest.skip("%s is not in this tree" % page_name)
    bad = []
    for href in _local_hrefs(page_name):
        url = "%s/%s" % (server, href)
        try:
            with urllib.request.urlopen(url, timeout=20) as r:
                status = r.status
                ctype = r.headers.get("content-type", "")
        except urllib.error.HTTPError as e:
            status, ctype = e.code, ""
        if status != 200:
            bad.append((href, status, ctype, "not served"))
        elif not ctype.split(";")[0].strip().startswith("text/"):
            # A browser downloads what it cannot render inline. A reader who
            # clicks a link to read terms must get the terms.
            bad.append((href, status, ctype, "downloads instead of rendering"))
    assert not bad, (
        "%s links to something the reader cannot read in place: %s" % (page_name, bad))


@pytest.mark.parametrize("linked", ["LICENSE.txt", "NOTICE.txt"])
def test_the_legal_text_is_published_with_a_renderable_extension(linked):
    assert os.path.exists(os.path.join(REPO, linked)), (
        "%s is missing. A static host cannot type an extensionless file and "
        "labels it application/octet-stream, which downloads rather than "
        "renders." % linked)


@pytest.mark.parametrize("original,copy", LEGAL_PAIRS)
def test_the_two_copies_of_each_legal_file_cannot_drift(original, copy):
    """`make legal` regenerates the copy; this asserts it was run."""
    a = os.path.join(REPO, original)
    b = os.path.join(REPO, copy)
    if not os.path.exists(a):
        pytest.skip("%s is not in this tree" % original)
    assert os.path.exists(b), "%s has not been generated from %s" % (copy, original)
    with open(a, "rb") as fh:
        want = fh.read()
    with open(b, "rb") as fh:
        got = fh.read()
    assert got == want, (
        "%s and %s have drifted apart. %s is generated by `make legal`; edit %s "
        "and re-run it." % (original, copy, copy, original))


@pytest.mark.parametrize("page_name", PAGES)
def test_no_page_still_links_the_extensionless_legal_files(page_name):
    path = os.path.join(REPO, page_name)
    if not os.path.exists(path):
        pytest.skip("%s is not in this tree" % page_name)
    with open(path, encoding="utf-8") as fh:
        html = fh.read()
    stale = re.findall(r'href="(LICENSE|NOTICE|LICENCE|COPYING)"', html)
    assert not stale, (
        "%s links the extensionless %s, which a static host serves as "
        "application/octet-stream" % (page_name, stale))
