#!/usr/bin/env python3
"""
build_ci_paths — generate the CI trigger paths from the Makefile and the manifest.

    python3 tools/build_ci_paths.py            # rewrite the generated block
    python3 tools/build_ci_paths.py --check    # fail if the workflow is out of date
    python3 tools/build_ci_paths.py --print    # show what the list would be

WHY
---
.github/workflows/build-api.yml runs `make derived` when a file in its `paths:`
filter changes. That list was maintained by hand and drifted from the build it is
meant to guard: it listed tools/enrich_coverage.py, which `make derived` no longer
runs, and it did NOT list tools/build_coverage_index.py or tools/build_web_payload.py,
which it does — so a change to either builder rebuilt nothing, silently. Nothing in
the repository could notice, because the same fact was written down twice.

It is now written down once. The list is DERIVED from two declarations that already
exist and are already tested:

  * the Makefile — which scripts `make derived` actually invokes, read out of the
    recipes of the `derived` target and its prerequisites;
  * data/MANIFEST.json — what each of those scripts reads (`inputs`).

plus the transitive local-import closure of each builder, because a change to
tools/web_payload.py changes data/web/* exactly as much as a change to its
entrypoint does, and the hand-written list could never have known that.

Two things are deliberately EXCLUDED, and their exclusion is the loop-safety
argument that the file's own comment used to assert without it being true:

  * every path the workflow COMMITS (the derived artifacts) — the old list included
    data/index.json, which the job both triggers on and writes back, so the job was
    one `[skip ci]` away from re-triggering itself;
  * data/media/** stays IN, because it is the only non-derived data input, and the
    job must never write it (the workflow asserts that).

`--check` runs in CI and in the test suite, so the list cannot drift again without
something turning red.
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from mediapaths import REPO  # noqa: E402

MAKEFILE = os.path.join(REPO, "Makefile")
MANIFEST = os.path.join(REPO, "data", "MANIFEST.json")
WORKFLOW = os.path.join(REPO, ".github", "workflows", "build-api.yml")

BEGIN = "      # --- generated by tools/build_ci_paths.py: do not edit by hand ---"
END = "      # --- end generated ---"

#: The build target whose inputs are the trigger.
TARGET = "derived"

#: Manifest generators that `make derived` legitimately does not run. Each needs a
#: reason, because "not in the build" is exactly the defect this file exists to
#: catch and an undocumented exception would hide the next one.
GENERATOR_EXCEPTIONS = {
    "tools/apply_verification.py":
        "writes data/_quarantine.json, a curation decision applied deliberately, "
        "not a derived artifact rebuilt on every data push",
}

#: Scripts `make derived` runs that legitimately declare no artifact of their own.
BUILD_SCRIPT_EXCEPTIONS = {
    "tools/build_manifest.py":
        "writes data/MANIFEST.json, the manifest itself, which cannot record its "
        "own digest; tools/build_manifest.py --check is what verifies it",
    "tools/verify_reference_tables.py":
        "a precondition, not a builder: it refuses the build when data/refs.json and "
        "the corpus disagree. It writes nothing, so it declares nothing — but a "
        "change to it still belongs in the trigger list, and it is there",
}

#: Non-script trigger paths, with the reason each is here.
EXTRA_PATHS = {
    "data/media/**": "the corpus every builder reads; the only non-derived data input",
    "Makefile": "the build itself — `make derived` is what the job runs",
    ".github/workflows/build-api.yml": "the job's own definition",
    "tools/build_ci_paths.py": "the generator of this very list",
}


# ------------------------------------------------------------------- Makefile


def parse_makefile(path: str = MAKEFILE) -> dict:
    """-> {target: {"prereqs": [...], "recipe": [...]}} for a simple Makefile."""
    targets: dict[str, dict] = {}
    cur = None
    rule = re.compile(r"^([A-Za-z0-9_.\-/ ]+):(?!=)\s*(.*)$")
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith("\t"):
                if cur:
                    targets[cur]["recipe"].append(line[1:])
                continue
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            m = rule.match(line)
            if not m:
                cur = None
                continue
            names, prereqs = m.group(1).split(), m.group(2).split()
            if names and names[0] == ".PHONY":
                cur = None
                continue
            for n in names:
                targets.setdefault(n, {"prereqs": [], "recipe": []})
                targets[n]["prereqs"] += prereqs
            cur = names[0]
    return targets


def scripts_of_target(targets: dict, name: str, seen=None) -> list[str]:
    """Every python script `make <name>` runs, following prerequisites."""
    seen = seen if seen is not None else set()
    if name in seen or name not in targets:
        return []
    seen.add(name)
    out = []
    for p in targets[name]["prereqs"]:
        out += scripts_of_target(targets, p, seen)
    for line in targets[name]["recipe"]:
        for m in re.finditer(r"\$\(PY\)\s+(-m\s+\S+|[^\s;]+\.py)", line):
            tok = m.group(1)
            if tok.startswith("-m"):
                continue
            out.append(tok)
    return out


# --------------------------------------------------------------- import closure


def local_imports(script_rel: str, seen: set) -> list[str]:
    """Repo-local modules a script imports, transitively.

    Stages and builders share code by importing a sibling module (build_web_payload
    -> web_payload, everything -> mediapaths). Those files are part of the build and
    a change to one changes the output, so they belong in the trigger list.
    """
    path = os.path.join(REPO, script_rel)
    if script_rel in seen or not os.path.exists(path):
        return []
    seen.add(script_rel)
    with open(path, encoding="utf-8") as fh:
        try:
            tree = ast.parse(fh.read(), filename=path)
        except SyntaxError:
            return []
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            names.add(node.module.split(".")[0])
    found = []
    here = os.path.dirname(path)
    for n in sorted(names):
        for cand in (os.path.join(here, n + ".py"), os.path.join(REPO, "tools", n + ".py"),
                     os.path.join(REPO, n + ".py")):
            if os.path.exists(cand):
                rel = os.path.relpath(cand, REPO)
                found.append(rel)
                found += local_imports(rel, seen)
                break
    return found


# --------------------------------------------------------------- the path list


def load_manifest() -> dict:
    with open(MANIFEST, encoding="utf-8") as fh:
        return json.load(fh)


def compute(verbose: bool = False) -> tuple[list[str], list[str]]:
    """-> (trigger paths, problems)."""
    problems = []
    targets = parse_makefile()
    build_scripts = sorted(set(scripts_of_target(targets, TARGET)))
    if not build_scripts:
        problems.append("no scripts found for `make %s` — the Makefile parse failed"
                        % TARGET)

    man = load_manifest()
    artifacts = man["artifacts"]
    declared_generators = set()
    for rel, e in artifacts.items():
        gen = e.get("generator", "")
        if gen.endswith(".py"):
            declared_generators.add(gen)

    # Every generator the manifest declares must be in the build, or be a declared
    # exception. This is the check the drift got past.
    for gen in sorted(declared_generators):
        if gen in build_scripts or gen in GENERATOR_EXCEPTIONS:
            continue
        problems.append(
            "data/MANIFEST.json names %s as a generator, but `make %s` does not run "
            "it and it is not in GENERATOR_EXCEPTIONS — either the artifact is never "
            "rebuilt, or the attribution is wrong (that was finding (e))."
            % (gen, TARGET))
    # ...and every script the build runs must produce something the manifest declares.
    for s in build_scripts:
        if s not in declared_generators and s not in BUILD_SCRIPT_EXCEPTIONS:
            problems.append(
                "`make %s` runs %s but data/MANIFEST.json declares no artifact it "
                "generates, so whatever it writes is unhashed and undetectable when "
                "it goes stale." % (TARGET, s))

    # inputs of the artifacts these scripts generate, minus the artifacts themselves
    artifact_paths = {rel.rstrip("/") for rel in artifacts}
    inputs = set()
    for rel, e in artifacts.items():
        if e.get("generator") not in build_scripts:
            continue
        for i in e.get("inputs") or []:
            i = i.strip()
            if not i or i.startswith("("):
                continue
            base = i.split("*")[0].rstrip("/")
            if base in artifact_paths or i in artifact_paths:
                continue                      # a derived artifact: never a trigger
            inputs.add(i.replace("/*.json", "/**"))

    closure = set(build_scripts)
    seen: set = set()
    for s in build_scripts:
        closure |= set(local_imports(s, seen))

    paths = sorted(closure | inputs | set(EXTRA_PATHS))
    # data/media/** subsumes data/media/*.json
    paths = [p for p in paths if p != "data/media" and p != "data/media/*.json"]
    if verbose:
        print("`make %s` runs: %s" % (TARGET, ", ".join(build_scripts)))
        print("import closure adds: %s"
              % ", ".join(sorted(closure - set(build_scripts))) or "(none)")
        print("declared inputs add: %s" % ", ".join(sorted(inputs)) or "(none)")
    return paths, problems


def render(paths: list[str]) -> str:
    lines = [BEGIN]
    lines += ['      - "%s"' % p for p in paths]
    lines.append(END)
    return "\n".join(lines)


def current_block(text: str) -> str | None:
    if BEGIN not in text or END not in text:
        return None
    start = text.index(BEGIN)
    end = text.index(END) + len(END)
    return text[start:end]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail if the workflow's generated block is out of date")
    ap.add_argument("--print", dest="show", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    a = ap.parse_args(argv)

    paths, problems = compute(verbose=a.verbose or a.show)
    for p in problems:
        print("CI PATHS PROBLEM:", p)
    want = render(paths)
    if a.show:
        print(want)
        return 1 if problems else 0

    with open(WORKFLOW, encoding="utf-8") as fh:
        text = fh.read()
    have = current_block(text)
    if have is None:
        print("CI PATHS PROBLEM: %s has no generated block. Add these two marker "
              "lines around the paths list:\n%s\n%s"
              % (os.path.relpath(WORKFLOW, REPO), BEGIN, END))
        return 1
    if a.check:
        if have != want:
            print("CI PATHS PROBLEM: the trigger list in %s is out of date with the "
                  "Makefile. Run `make ci-paths`. Diff:"
                  % os.path.relpath(WORKFLOW, REPO))
            hv = set(l.strip() for l in have.splitlines()[1:-1])
            wv = set(l.strip() for l in want.splitlines()[1:-1])
            for l in sorted(wv - hv):
                print("  MISSING  %s" % l)
            for l in sorted(hv - wv):
                print("  STALE    %s" % l)
            return 1
        print("CI trigger paths are current: %d entries derived from the Makefile "
              "and data/MANIFEST.json" % len(paths))
        return 1 if problems else 0

    if have != want:
        with open(WORKFLOW, "w", encoding="utf-8") as fh:
            fh.write(text.replace(have, want))
        print("updated %s: %d trigger paths" % (os.path.relpath(WORKFLOW, REPO),
                                                len(paths)))
    else:
        print("%s already current (%d trigger paths)"
              % (os.path.relpath(WORKFLOW, REPO), len(paths)))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
