#!/usr/bin/env python3
"""Evidence tiers for MediaDB component mappings.

One vocabulary, one place. `map_metabolite.Mapper` mints a tier for every mapping
it makes; this module additionally classifies the mapping_method values already
present in the shipped corpus, so a component that was written by some other
builder can be given an honest tier without re-guessing its identity.

THE RULE THIS FILE ENFORCES: a tier states what the mapping was ACTUALLY decided
on. It is never raised because the result looks right, and a route whose evidence
was destroyed gets the FLOOR of what it could have been, never the ceiling.
"""

# Ordered strongest to weakest. See map_metabolite.__doc__ for the definitions.
TIER_ORDER = [
    "structural_xref",      # source chemistry key resolved through the reverse index
    "curated_mapping",      # reviewed row in tools/curation/metabolite_corrections.tsv
    "author_asserted",      # a curator/recipe author asserted it; no chemical justification
    "source_bigg_id",       # the source supplied a BiGG id; an id-string route
    "exact_name",           # stereo-correct exact match against a BiGG name/synonym
    "name_table",           # hand-typed source-name -> BiGG table, unreviewed
    "fuzzy_name",           # normalised / alias / de-formula / heuristic name match
    "class_proxy",          # a class, vitamer group or element -> one species
    "derived_component",    # generated by the pipeline, not stated by the source
    "non_bigg_fallback",    # ModelSEED/MetaNetX/KEGG pseudo-exchange, not BiGG
    "unmappable_mixture",   # undefined mixture; no single exchange is defensible
    "unmapped",             # no confident target. Absent, not guessed.
]
TIER_RANK = {t: i for i, t in enumerate(TIER_ORDER)}

# Tiers that do NOT represent an observation of the medium's stated composition.
# Excluded from coverage arithmetic by operator decision (segregate and label).
#
# Only `derived_component` qualifies. An unmappable mixture and a refused mapping
# WERE stated by the source -- yeast extract really is in the medium; we simply
# cannot give it one exchange. They stay in the observed denominator and count as
# NOT COVERED, which is the honest way round: excluding them would flatter coverage
# by deleting the hardest cases, which is the defect this whole pass exists to undo.
NON_OBSERVED_TIERS = {"derived_component"}

# Tiers whose identity was decided by a name string rather than by chemistry.
NAME_BASED_TIERS = {"exact_name", "name_table", "fuzzy_name", "class_proxy"}

# --------------------------------------------------------------------------
# mapping_method (as shipped) -> (tier, remappable, note)
#
# `remappable` marks the routes whose stored component `name` is the string the
# mapping was actually made from, so re-running the corrected mapper on it is a
# genuine re-derivation rather than a circular re-read of the target's own name.
# --------------------------------------------------------------------------
METHOD_TIERS = {
    # --- structural: a source-supplied identifier hit the reverse index --------
    "inchikey":        ("structural_xref", False, "source InChIKey resolved"),
    "inchikey_remap":  ("structural_xref", False, "source InChIKey resolved"),
    "chebi":           ("structural_xref", False, "source ChEBI resolved"),
    "chebi_remap":     ("structural_xref", False, "source ChEBI resolved"),
    "kegg":            ("structural_xref", False, "source KEGG compound resolved"),
    "kegg_remap":      ("structural_xref", False, "source KEGG compound resolved"),
    "hmdb":            ("structural_xref", False, "source HMDB accession resolved"),
    "hmdb_remap":      ("structural_xref", False, "source HMDB accession resolved"),

    # --- the source itself supplied a BiGG identifier --------------------------
    "bigg_native":     ("source_bigg_id", False, "source supplied a BiGG id"),
    "mediadb_bigg":    ("source_bigg_id", False, "MediaDB (ISB) supplied a BiGG id"),

    # --- human-authored recipes and curation passes ----------------------------
    "curated":              ("author_asserted", False, "hand-authored record"),
    "wellknown_curation":   ("author_asserted", False, "tools/curate_wellknown_media.py template"),
    "growthdb_curation":    ("author_asserted", False, "GrowthDB curation pass"),
    "recipe":               ("author_asserted", False, "recipe transcription"),
    "carbon_source":        ("author_asserted", False, "curator-declared carbon source"),
    "mediadb_alias":        ("author_asserted", False, "MediaDB alias table"),
    "standard_formulation": ("author_asserted", False, "standard formulation"),

    # --- hand-typed source-name -> BiGG tables ---------------------------------
    # Unreviewed at the time of writing: MAP-05 proved chemistry errors inside them.
    "usda_nutrient":            ("name_table", False, "build_usda_media_v2.py NMAP_RAW"),
    "usda_mineral":             ("name_table", False, "build_usda_media_v2.py MINMAP"),
    "mediadive_salt":           ("name_table", False, "MediaDive salt dissociation table"),
    "mediadb_salt_dissociation": ("name_table", False, "MediaDB salt dissociation table"),
    "salt_dissociation_remap":  ("name_table", True,  "salt dissociation table"),
    "paper_salt_dissociation":  ("name_table", False, "salt dissociation table"),
    "remap_salt_dissociation":  ("name_table", True,  "salt dissociation table"),
    "salt_parse_remap":         ("name_table", True,  "salt name parse"),

    # --- name routes through this mapper (re-derivable from the stored name) ---
    "name":                          ("fuzzy_name", True, ""),
    "name_salt":                     ("fuzzy_name", True, ""),
    "name_alias":                    ("fuzzy_name", True, ""),
    "name_deformula":                ("fuzzy_name", True, ""),
    "name_acid_heuristic":           ("fuzzy_name", True, ""),
    "name_remap":                    ("fuzzy_name", True, ""),
    "name_alias_remap":              ("fuzzy_name", True, ""),
    "name_deformula_remap":          ("fuzzy_name", True, ""),
    "name_acid_heuristic_remap":     ("fuzzy_name", True, ""),
    "name_salt_remap":               ("fuzzy_name", True, ""),
    "name_alias_salt_remap":         ("fuzzy_name", True, ""),
    "name_deformula_salt_remap":     ("fuzzy_name", True, ""),
    "name_acid_heuristic_salt_remap": ("fuzzy_name", True, ""),
    "remap_name_deformula":          ("fuzzy_name", True, ""),
    "remap_name_alias":              ("fuzzy_name", True, ""),
    "remap_name_acid_heuristic":     ("fuzzy_name", True, ""),
    "name_foodb":                    ("fuzzy_name", True, ""),
    "name_alias_foodb":              ("fuzzy_name", True, ""),
    "name_deformula_foodb":          ("fuzzy_name", True, ""),
    "name_acid_heuristic_foodb":     ("fuzzy_name", True, ""),

    # --- routes whose evidence was destroyed: take the FLOOR -------------------
    # build_food_media_v2.py:64 discarded the per-compound method computed by
    # map_foodb_compounds.py, so the InChIKey/name split is unrecoverable. It is
    # NOT permissible to call these structural; the honest tier is the weaker one.
    "foodb_inchikey_name": ("fuzzy_name", False,
                            "PROVENANCE LOST: an unrecoverable mixture of InChIKey and "
                            "name hits; recorded at the weaker of the two"),
    "mediadive_defined":   ("fuzzy_name", False,
                            "PROVENANCE LOST: map_ingredients2.py passed name and ChEBI "
                            "together and kept neither as the match key"),

    # --- pipeline-generated, not stated by the cited source --------------------
    "hydrolysate_approximation": ("derived_component", False,
                                  "in-silico expansion of an undefined hydrolysate"),
    "complex_decomposition":     ("derived_component", False,
                                  "in-silico decomposition of a complex ingredient"),
    "mineral_base":              ("derived_component", False, "injected mineral base"),
    "base":                      ("derived_component", False, "injected base medium"),
    "base_medium_expansion":     ("derived_component", False, "injected base medium expansion"),
    "oxygen_regime":             ("derived_component", False, "pipeline-assigned oxygen regime"),
    "regime":                    ("derived_component", False, "pipeline-assigned regime"),

    # --- not a BiGG exchange ---------------------------------------------------
    "modelseed_fallback": ("non_bigg_fallback", False, "EX_cpd#####_e is not a BiGG id"),
    "kegg_fallback":      ("non_bigg_fallback", False, "EX_C#####_kegg_e is not a BiGG id"),
    "metanetx_fallback":  ("non_bigg_fallback", False, "EX_MNXM#_e is not a BiGG id"),
}


def tier_for_method(method):
    """(tier, remappable, note). Unknown methods get the floor, never the ceiling."""
    return METHOD_TIERS.get(method, ("fuzzy_name", False,
                                     f"unrecognised mapping_method {method!r}; "
                                     "recorded at the weakest name tier"))


def is_stronger(a, b):
    """True when tier `a` rests on stronger evidence than tier `b`."""
    return TIER_RANK.get(a, 99) < TIER_RANK.get(b, 99)
