#!/usr/bin/env python3
"""Metabolite -> BiGG exchange mapper for the Media repo.

Maps an external medium component (given a name and/or any cross-reference) to a
standard BiGG universal metabolite and its extracellular exchange reaction
(EX_<id>_e).

EVIDENCE TIERS
--------------
Every result carries `evidence_tier` -- what the mapping was ACTUALLY decided on --
and `match_key` -- the exact string that decided it, or None. The tier is minted
here and nowhere else, so no caller can stamp a confidence its evidence does not
support. Ordered strongest first:

  structural_xref    a source-supplied InChIKey/ChEBI/KEGG/HMDB/MNX/SEED resolved
                     through the reverse index. match_key = that identifier.
  curated_mapping    a reviewed row in tools/curation/metabolite_corrections.tsv,
                     carrying a written chemical justification and a verifier.
  source_bigg_id     the source itself supplied a BiGG identifier. An id-string
                     route, not a structural one.
  exact_name         the source string matches a BiGG name/synonym exactly and
                     the stereo descriptors agree (or neither declares one and no
                     stereoisomer ambiguity exists).
  name_table         a hand-typed source-name -> BiGG table, unreviewed.
  fuzzy_name         normalised / alias / de-formula / acid-heuristic / salt-
                     precleaned name match. A guess with a plausible basis.
  class_proxy        the source names a CLASS, vitamer group or element and one
                     representative species stands in for it. `proxy_for` lists
                     what was collapsed.
  derived_component  generated by the pipeline, not stated by the source.
  non_bigg_fallback  ModelSEED/MetaNetX/KEGG pseudo-exchange -- not BiGG.
  unmappable_mixture an undefined mixture; no single exchange is defensible.
  unmapped           no confident target. Absent, not guessed.

WHAT THIS MAPPER WILL NOT DO
----------------------------
* It will not resolve identity on a case-folded name when case or charge is the
  only discriminator (CO2 vs Co2+). Formula-shaped tokens go through
  chem_identity.resolve_formula_token first.
* It will not silently pick between stereoisomers. A declared L- must not land on
  a __D id; an undeclared query must not pick an enantiomer at random.
* It will not present the TARGET's cross-references as evidence for the mapping.
  `target_xref` describes the id that was chosen; `source_xref` is what the source
  actually supplied and is None when the source supplied nothing. `xref` is
  retained as a deprecated alias of `target_xref` for existing consumers.
* It will not overwrite the source's own compound string. `source_name` is
  returned verbatim; `name` (the BiGG display name) is kept for compatibility.

Usage:
    from map_metabolite import Mapper
    m = Mapper()  # loads tools/bigg_metabolite_dict.json + bigg_reverse_index.json
    hit = m.map(name="D-Glucose", inchikey="WQZGKKKJIJFFOK-GASJEMHNSA-N")
    # -> {"bigg_metabolite":"glc__D","exchange":"EX_glc__D_e", ...,
    #     "evidence_tier":"structural_xref","match_key":"WQZGKKKJIJFFOK-GASJEMHNSA-N"}
"""
import json, os, re

import chem_identity as CHEM

HERE = os.path.dirname(os.path.abspath(__file__))

# evidence_tier -> the legacy mapping_confidence vocabulary already understood by
# assets/media.js and DESIGN.md. Kept deliberately inside the existing vocabulary
# so a half-deployed browser cannot silently render a new tier as the calmest chip.
TIER_CONFIDENCE = {
    "structural_xref": "exact",
    "curated_mapping": "curated",
    "source_bigg_id": "inferred",
    "exact_name": "inferred",
    "name_table": "inferred",
    "fuzzy_name": "inferred",
    "class_proxy": "approximation",
    "derived_component": "convention",
    "non_bigg_fallback": "inferred",
    "unmappable_mixture": "approximation",
    "unmapped": "approximation",
}
TIER_ORDER = ["structural_xref", "curated_mapping", "source_bigg_id", "exact_name",
              "name_table", "fuzzy_name", "class_proxy", "derived_component",
              "non_bigg_fallback", "unmappable_mixture", "unmapped"]

def norm(s):
    s = (s or "").lower().strip()
    s = re.sub(r"^(l|d|dl)-", "", s)
    return re.sub(r"[^a-z0-9]", "", s)

_FORMULA = re.compile(r"^(?:[A-Z][a-z]?\d*){2,}$")
def strip_formula(name):
    """Drop a trailing molecular-formula token: 'Lactose C12H22O11' -> 'Lactose'."""
    parts = (name or "").rsplit(" ", 1)
    if len(parts) == 2 and any(c.isdigit() for c in parts[1]) and _FORMULA.match(parts[1]):
        return parts[0]
    return name

# Strip salts / hydrates / adducts / parentheticals so the underlying nutrient resolves:
#   "Calcium D-pantothenate" -> "D-pantothenate", "Thiamine HCl (vitamin B1)" -> "Thiamine",
#   "L-cysteine hydrochloride monohydrate" -> "L-cysteine", "Sodium ascorbate" -> "ascorbate".
_HYDRATE = re.compile(r"[·.*x×]\s*\d*\s*h2?\s*o\b", re.I)
_ADDUCT = re.compile(
    r"\b(?:hydrochlorides?|dihydrochlorides?|hydrobromides?|"
    r"(?:mono|di|tri|tetra|penta|hexa|hepta)?[- ]?hydrates?|anhydrous|hemi[- ]?calcium|"
    r"(?:mono|di|tri|hemi)?[- ]?(?:sodium|potassium|calcium|magnesium|ammonium|zinc|ferrous|ferric)\s+salt|"
    r"hcl|hbr|na\s*salt|k\s*salt|free\s*acid|free\s*base)\b", re.I)
_LEADCAT = re.compile(
    r"^\s*(?:di|mono|tri)?[- ]?(?:calcium|sodium|potassium|magnesium|ammonium|ferrous|ferric|"
    r"zinc|cupric|cuprous|manganous|lithium)[\s\-]+", re.I)
def preclean(name):
    """Best-effort removal of counterions / water of crystallisation / trivial adducts."""
    s = re.sub(r"\s*\([^)]*\)", " ", name or "")   # drop "(vitamin B1)", "(PABA)", "(TPP)"
    s = _HYDRATE.sub(" ", s)
    s = _ADDUCT.sub(" ", s)
    s = _LEADCAT.sub(" ", s)
    s = re.sub(r"[·*×]", " ", s)
    return re.sub(r"\s+", " ", s).strip(" -·.,")

# common-name -> BiGG id aliases (keyed by norm()). Fixes trivial misses like
# "acetic acid" (->ac), "O2", amino-acid full names, gases, organic acids.
_AA = {"alanine":"ala__L","arginine":"arg__L","asparagine":"asn__L","aspartate":"asp__L","asparticacid":"asp__L",
       "cysteine":"cys__L","glutamate":"glu__L","glutamicacid":"glu__L","glutamine":"gln__L","glycine":"gly",
       "histidine":"his__L","isoleucine":"ile__L","leucine":"leu__L","lysine":"lys__L","methionine":"met__L",
       "phenylalanine":"phe__L","proline":"pro__L","serine":"ser__L","threonine":"thr__L","tryptophan":"trp__L",
       "tyrosine":"tyr__L","valine":"val__L","ornithine":"orn","citrulline":"citr__L"}
_ALIASES = {**_AA,
    # gases / inorganics
    "o2":"o2","oxygen":"o2","dioxygen":"o2","co2":"co2","carbondioxide":"co2","h2":"h2","hydrogen":"h2",
    "n2":"n2","dinitrogen":"n2","h2s":"h2s","hydrogensulfide":"h2s","ch4":"ch4","methane":"ch4","co":"co",
    "carbonmonoxide":"co","no":"no","no2":"no2","no3":"no3","nitrate":"no3","nitrite":"no2","n2o":"n2o",
    "nh3":"nh4","ammonia":"nh4","ammonium":"nh4","h2o":"h2o","water":"h2o","proton":"h","phosphate":"pi",
    # organic acids (name "X acid" or "X-ic acid" -> conjugate base id)
    "aceticacid":"ac","acetate":"ac","aceticacidglacial":"ac","succinicacid":"succ","succinate":"succ",
    "lacticacid":"lac__L","lactate":"lac__L","dllacticacid":"lac__L","propionicacid":"ppa","propionate":"ppa",
    "propanoicacid":"ppa","butyricacid":"but","butyrate":"but","butanoicacid":"but","isobutyricacid":"isobut",
    "formicacid":"for","formate":"for","citricacid":"cit","citrate":"cit","pyruvicacid":"pyr","pyruvate":"pyr",
    # isovaleric acid: ival (Isovalerate, C5H9O2, in BiGGr) and 3mb share InChIKey
    # GWYFCOCPABKNJV-UHFFFAOYSA-M, but 3mb carries no formula and is not in BiGGr.
    "isovalericacid":"ival","3methylbutyricacid":"ival","isovalerate":"ival",
    "3methylbutanoicacid":"ival","3methylbutanoate":"ival","betamethylbutyricacid":"ival",
    "menaquinone4":"mqn4","mk4":"mqn4","menatetrenone":"mqn4",
    "fumaricacid":"fum","fumarate":"fum","malicacid":"mal__L","malate":"mal__L","oxalicacid":"oxa","oxalate":"oxa",
    "gluconicacid":"glcn","gluconate":"glcn","glycolicacid":"glyclt","glycolate":"glyclt","glyoxylicacid":"glx",
    "glyoxylate":"glx","alphaketoglutaricacid":"akg","2oxoglutaricacid":"akg","2oxoglutarate":"akg",
    "ketoglutaricacid":"akg","caproicacid":"hxa","hexanoicacid":"hxa",
    # alcohols / misc products (confident BiGG ids only)
    "ethanol":"etoh","methanol":"meoh","glycerol":"glyc","butanol":"btoh","1butanol":"btoh","nbutanol":"btoh",
    "indole":"indole","urea":"urea","putrescine":"ptrc","cadaverine":"15dap","spermidine":"spmd",
    # sugar-alcohol / sugar synonyms Biolog uses under non-BiGG names
    "dulcitol":"galt","galactitol":"galt","adonitol":"rbt","ribitol":"rbt","myoinositol":"inost",
    "iinositol":"inost","mesoinositol":"inost","dglucosamine":"gam","glucosamine":"gam",
    "nacetylglucosamine":"acgam","nacetyldglucosamine":"acgam","nacetylgalactosamine":"acgal__D",
    "2ketogluconate":"2dhguln","5ketogluconate":"5dglcn","sorbose":"srb__L","dmannitol":"mnl","mannitol":"mnl",
    "phenylacetate":"pac","phenylaceticacid":"pac","npropanol":"ppoh","propanol":"ppoh","1propanol":"ppoh",
    "betaine":"glyb","glycinebetaine":"glyb","sarcosine":"sarcs","valericacid":"M03134","pentanoate":"M03134",
    "valerate":"M03134","caproicacid":"caproic","hexanoate":"hxa","malonicacid":"malon","malonate":"malon",
    # ion charge-notation forms ("Ca2+", "SO42-", "Cl-") that source recipes use verbatim
    "ca2":"ca2","ca":"ca2","mg2":"mg2","mg":"mg2","so42":"so4","so4":"so4","cl":"cl","kion":"k","k":"k",
    "na":"na1","na1":"na1","fe2":"fe2","fe3":"fe3","fe":"fe3","nh4":"nh4","hco3":"hco3","bicarbonate":"hco3",
    "zn2":"zn2","zn":"zn2","cu2":"cu2","cu":"cu2","mn2":"mn2","mn":"mn2","co2ion":"cobalt2","cobalt":"cobalt2",
    "ni2":"ni2","ni":"ni2","po43":"pi","hpo42":"pi","h2po4":"pi","moo42":"mobd","molybdate":"mobd",
    # water forms that appear as components
    "water":"h2o","distilledwater":"h2o","deionizedwater":"h2o","dh2o":"h2o","ddh2o":"h2o","milliqwater":"h2o",
    "ultrapurewater":"h2o","sterilewater":"h2o",
    # --- food-nutrient recovery: mineral ELEMENT names reported by USDA/FooDB ---
    "phosphorus":"pi","phosphorusp":"pi","selenium":"slnt","seleniumse":"slnt","iron":"fe2","ironfe":"fe2",
    "zinc":"zn2","zinczn":"zn2","calcium":"ca2","calciumca":"ca2","magnesium":"mg2","magnesiummg":"mg2",
    "potassium":"k","potassiumk":"k","sodium":"na1","sodiumna":"na1","copper":"cu2","coppercu":"cu2",
    "manganese":"mn2","manganesemn":"mn2","molybdenum":"mobd","molybdenummo":"mobd","cobalt":"cobalt2",
    "nickel":"ni2","nickelni":"ni2","iodine":"iodine","iodinei":"iodine",
    # "chromium"/"chromium, Cr" deliberately NOT aliased: the only chromium species in
    # tools/bigg_metabolite_dict.json is cro4 (Chromate, CrO4) = Cr(VI), a toxic oxyanion
    # with dedicated reductases in several GEMs. Dietary/medium chromium is Cr(III).
    # There is no correct target, so the honest result is no mapping. See
    # tools/curation/metabolite_corrections.tsv row CHEM-CR-01.
    # --- vitamins / carotenoids reported as nutrient names ---
    "vitaminarae":"retinol","vitaminaiu":"retinol","vitamina":"retinol","retinolactivityequivalent":"retinol",
    "carotenebeta":"caro","betacarotene":"caro","tocopherolalpha":"avite1","alphatocopherol":"avite1",
    "vitaminealphatocopherol":"avite1","vitamine":"avite1","tocotrienolalpha":"avite2","alphatocotrienol":"avite2",
    "vitamind3cholecalciferol":"vitd3","cholecalciferol":"vitd3","vitamindd2d3":"vitd3",
    "vitamindd2d3internationalunits":"vitd3","vitamind":"vitd3","zeaxanthin":"zeax",
    # --- named fatty-acid classes -> dominant BiGG species (approximate) ---
    "pufa182":"lnlc","pufa182n6cc":"lnlc","pufa182cc":"lnlc","linoleicacid":"lnlc",
    "pufa183":"lnlnca","pufa183n3ccc":"lnlnca","alphalinolenicacid":"lnlnca",
    # n-6 C18:3 is GAMMA-linolenic acid (lnlncg, C18H29O2, VZCCETWTMQHEPK-QNEBEIHSSA-M),
    # NOT alpha-linolenic (lnlnca, n-3). Different double-bond positions, different compound.
    "pufa183n6ccc":"lnlncg","pufa183n6":"lnlncg",
    "pufa184":"strdnc","pufa204":"arachd","pufa205n3epa":"tmndnc","epa":"tmndnc","pufa226n3dha":"crvnc","dha":"crvnc",
    "mufa161":"hdcea","mufa161c":"hdcea","palmitoleicacid":"hdcea","mufa141":"ttdcea",
    "sfa150":"ptdca","pentadecanoicacid":"ptdca","sfa170":"hpdca","heptadecanoicacid":"hpdca",
    "sfa240":"lgnc","lignocericacid":"lgnc","sfa40":"but","butyricacid":"but","sfa60":"hxa","sfa80":"octa",
    "sfa100":"dca","sfa120":"ddca","sfa140":"ttdca","sfa160":"hdca","sfa180":"ocdca",
    # --- vitamin name/spelling variants already present in BiGG ---
    "riboflavine":"ribflv","thiamine":"thm","thiaminehydrochloride":"thm","thiaminhydrochloride":"thm",
    "pantothenicacid":"pnto__R","dpantothenicacid":"pnto__R","calciumpantothenate":"pnto__R",
    "retinol":"retinol","alltransretinol":"retinol","cyanocobalamin":"cbl1","vitaminb12":"cbl1",
    "phytomenadione":"phllqne","phylloquinone":"phllqne","vitamink":"phllqne","vitamink1":"phllqne",
    "vitaminkphylloquinone":"phllqne","vitaminkdihydrophylloquinone":"phllqne",
    "betacryptoxanthin":"bcryptox","cryptoxanthinbeta":"bcryptox","alphacryptoxanthin":"crpxan",
    # --- more fatty acids (IUPAC / class names) -> clean BiGG species ---
    "eicosapentaenoicacid":"tmndnc","docosahexaenoicacid":"crvnc","sfa220":"behen","behenicacid":"behen",
    "pufa203n6":"dlnlcg","pufa203":"dlnlcg","dihomogammalinolenicacid":"dlnlcg",
    "c181n9":"ocdcea","oleicacid":"ocdcea","zz912octadecadienoicacid":"lnlc","c182n6":"lnlc","c183n3":"lnlnca",
    # --- sugar anomers / pyranose-furanose synonyms -> the parent BiGG sugar ---
    "betadglucopyranose":"glc__D","alphadglucopyranose":"glc__D","glucopyranose":"glc__D",
    "betadglucose":"glc__D","alphadglucose":"glc__D","dextrose":"glc__D",
    "betadfructofuranose":"fru","alphadfructofuranose":"fru","fructofuranose":"fru","betadfructose":"fru",
    "betadgalactopyranose":"gal","alphadgalactopyranose":"gal","galactopyranose":"gal","betadgalactose":"gal",
    "betadmannopyranose":"man","alphadmannopyranose":"man","mannopyranose":"man","betadmannose":"man","alphadmannose":"man",
    "betadxylopyranose":"xyl__D","xylopyranose":"xyl__D","alphalarabinofuranose":"arab__L",
    # --- amino-acid / metabolite synonyms ---
    "hydroxyproline":"4hpro_LT","4hydroxyproline":"4hpro_LT","trans4hydroxyproline":"4hpro_LT",
    "hydroxylproline":"4hpro_LT","4hydroxylproline":"4hpro_LT","transhydroxyproline":"4hpro_LT",
    "octanoicacid":"octa","octanoate":"octa","caprylicacid":"octa","caprylate":"octa","noctanoicacid":"octa",
    "cobalamin":"cbl1","hydroxocobalamin":"cbl1","hydroxycobalamin":"cbl1","aquocobalamin":"cbl1",
    "vitamind3":"vitd3","cholecalciferol":"vitd3","calciol":"vitd3",
    # gamma-linolenic acid is C18:3 n-6 (lnlncg). dlnlcg is DIHOMO-gamma-linolenic, C20:3 n-6
    # (C20H33O2) -- two carbons longer, a different metabolite.
    "gamolenicacid":"lnlncg","gammalinolenicacid":"lnlncg","glaacid":"lnlncg",
    "dihomogammalinolenicacid":"dlnlcg","pufa203n6":"dlnlcg",
    "doconexent":"crvnc","docosahexaenoate":"crvnc","icosapent":"tmndnc","eicosapentaenoate":"tmndnc",
    # --- elements/ions that DO exist as BiGG metabolites ---
    "chlorine":"cl","chloride":"cl","chlorinecl":"cl","mercury":"hg2","mercuryhg":"hg2",
    "lead":"pb","leadpb":"pb","cadmium":"cd2","cadmiumcd":"cd2","cadmium2":"cd2",
    # --- saturated fatty-acid classes with a clean BiGG species ---
    "sfa200":"arach","arachidicacid":"arach","eicosanoicacid":"arach","icosanoicacid":"arach",
    # --- mono/polyunsaturated fatty-acid classes -> dominant BiGG species (approximate) ---
    "mufa201":"M01235","mufa201c":"M01235","gadoleicacid":"M01235","gondoicacid":"M01235","eicosenoicacid":"M01235",
    "mufa171":"hepedecacid","mufa171c":"hepedecacid","heptadecenoicacid":"hepedecacid",
    "mufa221":"doco13ac","mufa221c":"doco13ac","erucicacid":"doco13ac",
    "mufa241":"nrvnc","mufa241c":"nrvnc","nervonicacid":"nrvnc",
    "pufa204":"arachd","pufa204n6":"arachd","arachidonicacid":"arachd",
    "pufa202":"M00008","pufa202n6":"M00008","pufa202n6cc":"M00008","eicosadienoicacid":"M00008"}

# Vitamins / cofactors / common salt-form synonyms across databases (keyed by norm();
# every target verified present in the BiGG dict). Salt forms are also handled by preclean().
_ALIASES.update({
    # p-aminobenzoate (PABA)
    "4aminobenzoicacid":"4abz","paminobenzoicacid":"4abz","paraaminobenzoicacid":"4abz",
    "paraaminobenzoate":"4abz","paba":"4abz","4aminobenzoate":"4abz","aminobenzoicacid":"4abz",
    "paminobenzoate":"4abz","4aminobenzoicacidpaba":"4abz",
    # lipoic / thioctic acid
    "lipoicacid":"lipoate","alphalipoicacid":"lipoate","thiocticacid":"lipoate","lipoate":"lipoate",
    "68thiocticacid":"lipoate","thioctate":"lipoate","alphalipoate":"lipoate","6thiocticacid":"lipoate",
    # nicotinamide / niacin
    "nicotinamide":"ncam","nicotineamide":"ncam","niacinamide":"ncam","nicotinicacidamide":"ncam",
    "niacin":"nac","nicotinicacid":"nac","nicotinate":"nac","pyridine3carboxylicacid":"nac",
    # inositol
    "inositol":"inost","myoinositol":"inost","mesoinositol":"inost","iinositol":"inost","cyclohexanehexol":"inost",
    # pantothenate (calcium/greek salt forms handled by preclean too)
    "pantothenate":"pnto__R","pantothenicacid":"pnto__R","dpantothenate":"pnto__R",
    "capantothenate":"pnto__R","cadpantothenate":"pnto__R","pantothenatecalcium":"pnto__R",
    "hemicalciumpantothenate":"pnto__R","vitaminb5":"pnto__R",
    # choline
    "choline":"chol","cholinechloride":"chol","cholinebitartrate":"chol","cholinecl":"chol",
    # thiamine pyrophosphate (TPP / cocarboxylase)
    "thiaminepyrophosphate":"thmpp","thiaminpyrophosphate":"thmpp","thiaminediphosphate":"thmpp",
    "thiamindiphosphate":"thmpp","cocarboxylase":"thmpp","tpp":"thmpp",
    # glutathione (reduced)
    "glutathione":"gthrd","reducedglutathione":"gthrd","glutathionereduced":"gthrd","gsh":"gthrd",
    "glutathionelreduced":"gthrd",
    # pyridoxine / pyridoxal / pyridoxamine (vitamin B6)
    "pyridoxine":"pydxn","pyridoxol":"pydxn","vitaminb6":"pydxn","pyridoxinehydrochloride":"pydxn",
    "pyridoxal":"pydx","pyridoxamine":"pydam",
    # biotin (vitamin B7/H)
    "biotin":"btn","biotine":"btn","vitaminh":"btn","vitaminb7":"btn","dbiotin":"btn",
    # ascorbate (vitamin C)
    "ascorbate":"ascb__L","ascorbicacid":"ascb__L","sodiumascorbate":"ascb__L","vitaminc":"ascb__L",
    # thiamine (vitamin B1) extras
    "thiaminechloride":"thm","vitaminb1":"thm","thiaminmononitrate":"thm","thiaminemononitrate":"thm",
    "aneurine":"thm",
    # riboflavin (vitamin B2)
    "riboflavin":"ribflv","vitaminb2":"ribflv","lactoflavin":"ribflv",
    # folate (vitamin B9)
    "folicacid":"fol","folate":"fol","vitaminb9":"fol","pteroylglutamicacid":"fol","pteroylmonoglutamicacid":"fol",
    # menaquinone (vitamin K2) — approximate to menaquinone-8
    "menaquinone":"mqn8","vitamink2":"mqn8",
    # a few more common cofactors / spelling variants
    "cyanocobalamine":"cbl1","cobalamine":"cbl1","hydroxocobalamine":"cbl1",
    "tetrahydrofolate":"thf","tetrahydrofolicacid":"thf","5methyltetrahydrofolate":"5mthf",
    "nad":"nad","nicotinamideadeninedinucleotide":"nad","betanad":"nad","vfactor":"nad",
    "nadp":"nadp","nicotinamideadeninedinucleotidephosphate":"nadp",
    "nicotinamidemononucleotide":"nmn","pyridoxal5phosphate":"pydx5p","pyridoxalphosphate":"pydx5p",
})
# Fatty acids (common + IUPAC + salt/ester names) -> BiGG species; organic acids;
# nucleosides. All targets verified present in the BiGG dict and name-checked.
_ALIASES.update({
    # saturated fatty acids by common + systematic name (norm strips a leading n-)
    "caproicacid":"hxa","hexanoicacid":"hxa","caproate":"hxa","hexanoate":"hxa",
    "caprylicacid":"octa","octanoicacid":"octa","caprylate":"octa","octanoate":"octa",
    "capricacid":"dca","decanoicacid":"dca","caprate":"dca","decanoate":"dca",
    "lauricacid":"ddca","dodecanoicacid":"ddca","laurate":"ddca","dodecanoate":"ddca",
    "myristicacid":"ttdca","tetradecanoicacid":"ttdca","myristate":"ttdca","tetradecanoate":"ttdca",
    "pentadecanoicacid":"ptdca","pentadecanoate":"ptdca","pentadecylicacid":"ptdca",
    "palmiticacid":"hdca","hexadecanoicacid":"hdca","palmitate":"hdca","hexadecanoate":"hdca","cetylicacid":"hdca",
    "stearicacid":"ocdca","octadecanoicacid":"ocdca","stearate":"ocdca","octadecanoate":"ocdca",
    "arachidicacid":"arach","eicosanoicacid":"arach","icosanoicacid":"arach","arachidate":"arach",
    "behenicacid":"behen","docosanoicacid":"behen","behenate":"behen","docosanoate":"behen",
    "lignocericacid":"lgnc","tetracosanoicacid":"lgnc","lignocerate":"lgnc",
    # unsaturated fatty acids
    "palmitoleicacid":"hdcea","palmitoleate":"hdcea","hexadecenoicacid":"hdcea","9hexadecenoicacid":"hdcea",
    "myristoleicacid":"ttdcea","myristoleate":"ttdcea","tetradecenoicacid":"ttdcea","9tetradecenoicacid":"ttdcea",
    "oleicacid":"ocdcea","oleate":"ocdcea","octadecenoicacid":"ocdcea","cisoleicacid":"ocdcea",
    "linoleicacid":"lnlc","linoleate":"lnlc","octadecadienoicacid":"lnlc",
    "linolenicacid":"lnlnca","linolenate":"lnlnca","alphalinolenicacid":"lnlnca","octadecatrienoicacid":"lnlnca",
    # short / branched-chain acids
    "butyricacid":"but","nbutyricacid":"but","butanoicacid":"but","butyrate":"but","nbutyrate":"but",
    "isobutyricacid":"2mpa","2methylpropanoicacid":"2mpa","isobutyrate":"2mpa","2methylpropanoate":"2mpa",
    # (isovalerate targets consolidated on `ival` above -- 3mb has no formula and is not in BiGGr)
    "3hydroxybutyricacid":"bhb","betahydroxybutyricacid":"bhb","3hydroxybutyrate":"bhb","3hydroxybutanoicacid":"bhb",
    "3hydroxyisobutyricacid":"3hmp","3hydroxyisobutyrate":"3hmp","3hydroxy2methylpropanoicacid":"3hmp",
    "polyhydroxybutyricacid":"phb","polybetahydroxybutyricacid":"phb","polyhydroxybutyrate":"phb","poly3hydroxybutyricacid":"phb","polyrhydroxybutyricacid":"phb",
    # orotic acid (pyrimidine intermediate, characteristic milk acid)
    "oroticacid":"orot","orotate":"orot",
    # GABA
    "gammaaminobutyricacid":"4abut","4aminobutyricacid":"4abut","4aminobutanoicacid":"4abut","gaba":"4abut","aminobutyricacid":"4abut","4aminobutyrate":"4abut","4aminobutanoate":"4abut",
    # nucleosides
    "adenosine":"adn","guanosine":"gsn","cytidine":"cytd","uridine":"uri","inosine":"ins",
    "thymidine":"thymd","deoxyguanosine":"dgsn","2deoxyguanosine":"dgsn","deoxyadenosine":"dad_2",
    "2deoxyadenosine":"dad_2","xanthosine":"xtsn","hypoxanthine":"hxan","xanthine":"xan",
})

class Mapper:
    def __init__(self, base=HERE):
        # every refusal is recorded so an ambiguity list can be reviewed rather
        # than silently absorbed into a guess
        self.refusals = []
        self.dict = json.load(open(os.path.join(base, "bigg_metabolite_dict.json")))
        ri = json.load(open(os.path.join(base, "bigg_reverse_index.json")))
        self.name_idx = ri["name"]
        self.name_strict = ri["name_strict"]
        self.xref_idx = ri["xref"]           # {inchikey:{...}, chebi:{...}, kegg:{...}, hmdb:{...}, mnx:{...}, seed:{...}}
        # keep only aliases whose target id actually exists (avoid mismapping to a bogus id)
        self.aliases = {k: v for k, v in _ALIASES.items() if v in self.dict}
        # ChEBI/KEGG -> MNXM -> ModelSEED/KEGG fallback (for substrates with no BiGG exchange)
        try:
            fb = json.load(open(os.path.join(base, "xref_fallback.json")))
            self.chebi2mnx, self.kegg2mnx = fb["chebi2mnx"], fb["kegg2mnx"]
            self.mnx2seed, self.mnx2kegg = fb["mnx2seed"], fb["mnx2kegg"]
            self.name2mnx = fb.get("name2mnx", {})
        except Exception:
            self.chebi2mnx = self.kegg2mnx = self.mnx2seed = self.mnx2kegg = self.name2mnx = {}
        # index BiGG names with the trailing molecular formula stripped, e.g.
        # "Lactose C12H22O11" -> "lactose". This recovers hundreds of common sugars/substrates.
        self.name_nf = {}
        for bid, rec in self.dict.items():
            nm = strip_formula(rec.get("name", ""))
            k = norm(nm)
            if k:
                self.name_nf.setdefault(k, []).append(bid)
        # stereo families: 'ser' -> {'ser','ser__D','ser__L'}. Used to read the
        # enantiomer an UNSUFFIXED id stands for, from the ids BiGG does resolve.
        self.stereo_family = {}
        for bid in self.dict:
            self.stereo_family.setdefault(CHEM.id_stereo_base(bid), set()).add(bid)
        # InChIKey -> the in_biggr id(s) carrying it. Used to replace a chemistry-free,
        # out-of-reactome target with the reactome id that is PROVABLY the same
        # compound (3mb -> ival). Keyed on the full InChIKey, so it can never merge
        # two different compounds or two enantiomers.
        self.ik_biggr = {}
        for bid, rec in self.dict.items():
            ik = (rec.get("xrefs") or {}).get("inchikey")
            if ik and rec.get("in_biggr"):
                self.ik_biggr.setdefault(str(ik).upper(), []).append(bid)
        # stereo-PRESERVING de-formula index: BiGG writes 'L Ornithine C5H13N2O2',
        # which the stereo-stripping norm() flattens onto plain 'ornithine'. Keying
        # it without stripping keeps 'lornithine' -> orn__L reachable.
        self.name_strict_nf = {}
        for bid, rec in self.dict.items():
            k = re.sub(r"[^a-z0-9]", "", strip_formula(rec.get("name", "")).lower())
            if k:
                self.name_strict_nf.setdefault(k, []).append(bid)

    def _prefer(self, ids):
        """dedupe; prefer BiGGr-present ids, then shortest id (usually the canonical).

        RETAINED for backwards compatibility only. It sorts, it never decides:
        for enantiomers both candidates are in_biggr and the same length, so the
        tie falls through to insertion order. Use _choose() for decisions.
        """
        seen, uniq = set(), []
        for i in ids:
            if i not in seen:
                seen.add(i); uniq.append(i)
        uniq.sort(key=lambda i: (0 if self.dict.get(i, {}).get("in_biggr") else 1, len(i)))
        return uniq

    # ---- chemistry-aware candidate resolution ---------------------------------

    def _ik(self, bid):
        return (self.dict.get(bid, {}).get("xrefs") or {}).get("inchikey")

    def _formula(self, bid):
        return (self.dict.get(bid, {}).get("xrefs") or {}).get("formula")

    def _chemically_distinct(self, ids):
        """True when the candidates are not the same compound.

        Distinct means: different InChIKey skeletons, or heavy-atom formulas that
        disagree. Enantiomers are NOT distinct by this test (same skeleton, same
        formula) -- they are separated by the stereo gate instead.
        """
        sks = {CHEM.ik_skeleton(self._ik(i)) for i in ids}
        sks.discard(None)
        if len(sks) > 1:
            return True
        for a in ids:
            for b in ids:
                if a < b and CHEM.formulas_disagree(self._formula(a), self._formula(b)):
                    return True
        return False

    def _implied_stereo(self, bid, siblings):
        """The enantiomer a BiGG id stands for, using its suffix or its siblings.

        'ser__L' -> 'L' from the suffix. An UNSUFFIXED id ('orn') is inferred to be
        the complement of a suffixed sibling on the same skeleton: if 'orn__D'
        exists and carries a different InChIKey stereo layer, then 'orn' is the
        L-form. Returns None when nothing decides it.
        """
        s = CHEM.stereo_of_id(bid)
        if s:
            return s
        base = CHEM.id_stereo_base(bid)
        # Consult the whole dictionary, not just the candidate list: 'gal' is the
        # D-sugar because 'gal__L' exists in BiGG with a different stereo layer,
        # whether or not gal__L happened to be a candidate for this query.
        others = {CHEM.stereo_of_id(o) for o in self.stereo_family.get(base, ())
                  if o != bid}
        others.discard(None)
        if len(others) == 1:
            other = others.pop()
            partner = f"{base}__{other}"
            if CHEM.same_stereo(self._ik(bid), self._ik(partner)) is False:
                return "L" if other == "D" else "D"
        return None

    def _choose(self, ids, want_stereo=None, strict=False):
        """Pick one candidate by chemistry, or refuse.

        Returns (bigg_id, qualifier, refusal_reason). Exactly one of bigg_id /
        refusal_reason is set. `qualifier` is 'stereo_matched', 'stereo_absent',
        'unique' or 'preferred'.
        """
        uniq = self._prefer(ids)
        if not uniq:
            return None, None, "no_candidates"

        if want_stereo in ("L", "D"):
            matched = [i for i in uniq if self._implied_stereo(i, uniq) == want_stereo]
            if len(matched) == 1:
                return matched[0], "stereo_matched", None
            if len(matched) > 1:
                if self._chemically_distinct(matched):
                    return None, None, ("ambiguous_after_stereo_gate: " + ",".join(matched))
                return self._prefer(matched)[0], "stereo_matched", None
            # Nothing carries the requested stereochemistry. An id with NO descriptor
            # is acceptable only when there is positive reason to read it as this
            # enantiomer -- i.e. no stereo-suffixed candidate exists at all (glycine
            # is achiral; 'gly' is the only glycine). If a suffixed candidate DOES
            # exist and it is the wrong enantiomer, refuse: picking the unsuffixed
            # neighbour would be a guess (L-glucose is not beta-D-glucose).
            suffixed = [i for i in uniq if CHEM.stereo_of_id(i)]
            undeclared = [i for i in uniq if self._implied_stereo(i, uniq) is None]
            if suffixed:
                return None, None, (f"source declares {want_stereo}- but the only stereo-resolved "
                                    f"candidates are "
                                    f"{'/'.join(sorted(set(CHEM.stereo_of_id(i) for i in suffixed)))}"
                                    f"-: " + ",".join(uniq))
            if undeclared and not self._chemically_distinct(undeclared):
                return self._prefer(undeclared)[0], "stereo_absent", None
            return None, None, ("no candidate carries the declared stereochemistry: " + ",".join(uniq))

        if want_stereo == "DL":
            # a racemate is not one BiGG metabolite; refuse rather than pick a half
            stereo_ids = [i for i in uniq if CHEM.stereo_of_id(i)]
            if stereo_ids:
                return None, None, ("source declares DL (racemate); candidates are "
                                    "single enantiomers: " + ",".join(uniq))

        if len(uniq) == 1:
            return uniq[0], "unique", None

        # No stereo declared by the source.
        if self._chemically_distinct(uniq):
            return None, None, ("chemically distinct candidates share one name key: "
                                + ",".join(uniq))
        stereo_ids = [i for i in uniq if CHEM.stereo_of_id(i)]
        if stereo_ids:
            # Only a candidate that is literally the stereo-base of a suffixed
            # candidate counts as "the unresolved form" (orn for orn__D). An
            # unrelated unsuffixed id (glc__bD beside glc__D) does not.
            bases = {CHEM.id_stereo_base(i) for i in stereo_ids}
            plain = [i for i in uniq if not CHEM.stereo_of_id(i) and i in bases]
            if plain:
                return self._prefer(plain)[0], "preferred", None
            if len({CHEM.stereo_of_id(i) for i in stereo_ids}) > 1:
                return None, None, ("source declares no stereochemistry but every "
                                    "candidate is a single enantiomer: " + ",".join(uniq))
        return uniq[0], "preferred", None

    # ---- result construction --------------------------------------------------

    def _result(self, bid, method, tier, match_key=None, match_field=None,
                source_name=None, source_xref=None, proxy_for=None, note=None):
        """Mint a mapping result. The ONLY place a tier/confidence is created."""
        rec = self.dict.get(bid, {})
        # CHEMISTRY SUBSTITUTION: if the chosen id is absent from the reference
        # reactome but an in_biggr id carries the IDENTICAL InChIKey, they are the
        # same compound and the reactome id is the usable one. Keyed on the full
        # InChIKey (skeleton + stereo + protonation), so enantiomers never merge.
        if bid in self.dict and not rec.get("in_biggr"):
            ik = (rec.get("xrefs") or {}).get("inchikey")
            f0 = (rec.get("xrefs") or {}).get("formula")
            alts = [a for a in self.ik_biggr.get(str(ik).upper(), []) if a != bid] if ik else []
            # belt and braces: identical InChIKey AND a non-contradicting formula.
            alts = [a for a in alts
                    if not CHEM.formulas_disagree(f0, (self.dict[a].get("xrefs") or {}).get("formula"))]
            if len(alts) == 1:
                note = ((note + "; ") if note else "") + (
                    f"target {bid} is absent from the BiGGr reactome; substituted "
                    f"{alts[0]}, which carries the identical InChIKey {ik}")
                bid = alts[0]
                rec = self.dict.get(bid, {})
        target_xref = rec.get("xrefs", {})
        # HONESTY CAP: a name match cannot be called exact when the chosen target
        # carries no structure in our own dictionary -- there is nothing the match
        # could have been checked against. 'choles', 'b12', 'mops' and 'cystine__L'
        # are all in this class.
        if tier == "exact_name" and not (target_xref.get("inchikey") or target_xref.get("formula")):
            tier = "fuzzy_name"
            note = ((note + "; ") if note else "") + (
                f"target {bid} carries no InChIKey and no formula in "
                "tools/bigg_metabolite_dict.json, so the name match could not be "
                "checked against structure")
        # match_key is reserved for IDENTIFIERS. A name is not an identifier, and the
        # single worst defect in this resource was a name lookup presented as though a
        # cross-reference had confirmed it. Name evidence is recorded separately.
        matched_name = None
        if tier in ("exact_name", "name_table", "fuzzy_name", "class_proxy"):
            matched_name, match_key = match_key, None
        out = {
            "bigg_metabolite": bid,
            "exchange": f"EX_{bid}_e",
            "name": rec.get("name", bid),          # legacy: the BiGG display name
            "target_name": rec.get("name", bid),
            "source_name": source_name,            # verbatim source string, never overwritten
            "in_biggr": rec.get("in_biggr", False),
            "target_xref": target_xref,            # describes the CHOSEN id
            "xref": target_xref,                   # deprecated alias of target_xref
            "source_xref": source_xref or None,    # what the source supplied; None = nothing
            "match_key": match_key,                # the exact IDENTIFIER that decided it
            "matched_name": matched_name,          # the exact NAME string that matched
            "match_field": match_field,
            "evidence_tier": tier,
            "mapping_method": method,
            "mapping_confidence": TIER_CONFIDENCE.get(tier, "inferred"),
        }
        if proxy_for:
            out["proxy_for"] = list(proxy_for)
        if note:
            out["mapping_note"] = note
        return out

    @staticmethod
    def _refusal_kind(reason):
        r = (reason or "").lower()
        if "no candidate matched" in r:
            return "no_match"
        if "racemate" in r:
            return "racemate"
        if "declares" in r and "stereo" in r or "stereochemistry" in r:
            return "stereo_conflict"
        if "chemically ambiguous" in r or "chemically distinct" in r or "ambiguous" in r:
            return "chemically_ambiguous"
        if "formula token refused" in r:
            return "refused_token"
        return "other"

    def _refuse(self, source_name, reason, source_xref=None):
        """Record and return an explicit non-mapping. Absent, never guessed."""
        self.refusals.append({"source_name": source_name, "reason": reason,
                              "kind": self._refusal_kind(reason)})
        return {
            "bigg_metabolite": None, "exchange": None,
            "name": source_name, "target_name": None, "source_name": source_name,
            "in_biggr": False, "target_xref": {}, "xref": {},
            "source_xref": source_xref or None,
            "match_key": None, "match_field": None,
            "evidence_tier": "unmapped", "mapping_method": "unmapped",
            "mapping_confidence": TIER_CONFIDENCE["unmapped"],
            "refusal_kind": self._refusal_kind(reason),
            "mapping_note": reason,
        }

    @staticmethod
    def _norm_xref(key, val):
        v = str(val).strip()
        if key == "inchikey": return v.upper()
        if key in ("chebi", "hmdb"): return re.sub(r"\D", "", v).lstrip("0") or "0"
        return v

    def fallback_exchange(self, chebi=None, kegg=None, name=None):
        """No BiGG exchange -> formulate a valid one from ModelSEED via MetaNetX (EX_cpd#####_e),
        else KEGG (EX_C#####_kegg_e), else MetaNetX (EX_MNXM#_e). Resolves via ChEBI, KEGG, or name."""
        mnx = None
        if chebi:
            c = str(chebi).replace("CHEBI:", "").strip()
            mnx = self.chebi2mnx.get(c) or self.chebi2mnx.get("CHEBI:" + c)
        if not mnx and kegg:
            mnx = self.kegg2mnx.get(str(kegg).strip())
        if not mnx and name:
            mnx = self.name2mnx.get(norm(name))
        if not mnx:
            return None
        seed = self.mnx2seed.get(mnx); kg = self.mnx2kegg.get(mnx)
        base = {"bigg_metabolite": None, "in_biggr": False, "mnx": mnx,
                "source_name": name, "evidence_tier": "non_bigg_fallback",
                "mapping_confidence": TIER_CONFIDENCE["non_bigg_fallback"],
                "match_key": str(chebi or kegg or name), "target_xref": {}, "xref": {},
                "mapping_note": "no BiGG exchange exists for this compound; the exchange id "
                                "below is NOT a BiGG identifier and no BiGG model will accept it"}
        if seed:
            return {**base, "exchange": f"EX_{seed}_e", "namespace": "modelseed", "ref_id": seed,
                    "mapping_method": "modelseed_fallback"}
        if kg:
            return {**base, "exchange": f"EX_{kg}_kegg_e", "namespace": "kegg", "ref_id": kg,
                    "mapping_method": "kegg_fallback"}
        return {**base, "exchange": f"EX_{mnx}_e", "namespace": "metanetx", "ref_id": mnx,
                "mapping_method": "metanetx_fallback"}

    def map(self, name=None, inchikey=None, chebi=None, kegg=None, hmdb=None, mnx=None, seed=None,
            strict=False):
        """Resolve a component. Returns a result dict, or None when nothing matched.

        `strict=True` returns an explicit `unmapped` result (with the reason)
        instead of None wherever the mapper refuses, so a caller can record the
        refusal rather than fall through to a weaker guess.
        """
        src_xref = {k: v for k, v in (("inchikey", inchikey), ("chebi", chebi), ("kegg", kegg),
                                      ("hmdb", hmdb), ("mnx", mnx), ("seed", seed)) if v}
        # 1) cross-references -- the only structural route. match_key is the
        #    SOURCE's identifier, not the target's.
        for key, val in (("inchikey", inchikey), ("chebi", chebi), ("kegg", kegg),
                         ("hmdb", hmdb), ("mnx", mnx), ("seed", seed)):
            if not val:
                continue
            bid = self.xref_idx.get(key, {}).get(self._norm_xref(key, val))
            if bid:
                return self._result(bid, key, "structural_xref", match_key=str(val),
                                    match_field=key, source_name=name, source_xref=src_xref)
        # A supplied identifier that the index does not know is a MISS, and must be
        # recorded as one -- it must never be silently replaced by the target's own
        # identifier further down the name path.
        xref_miss = bool(src_xref)

        # 2) name -- raw first, then a salt/hydrate/adduct-stripped version
        if name:
            r = self._by_name(name, source_xref=src_xref)
            if r is not None and r.get("bigg_metabolite"):
                if xref_miss:
                    r["mapping_note"] = ("source supplied " + ",".join(sorted(src_xref)) +
                                         " which is absent from the reverse index (xref_miss); "
                                         "resolved by name instead")
                return r
            refusal = r if r is not None else None
            # A parenthetical often carries the SPECIFIC identity that the bare head
            # word loses: "Vitamin K (Menaquinone-4)" is MK-4, not phylloquinone.
            # Try it before precleaning strips it away.
            for inner in re.findall(r"\(([^)]*)\)", name):
                inner = inner.strip()
                if not inner or inner.lower() == (name or "").lower():
                    continue
                ri = self._by_name(inner, source_xref=src_xref, original_name=name)
                if ri is not None and ri.get("bigg_metabolite"):
                    ri["mapping_method"] += "_paren"
                    ri["mapping_note"] = ((ri.get("mapping_note") + "; ") if ri.get("mapping_note") else "") + \
                        f"resolved from the parenthetical qualifier {inner!r}, which is more specific than the head term"
                    return ri
                refusal = refusal or ri
            pc = preclean(name)
            if pc and pc.lower() != (name or "").lower():
                r2 = self._by_name(pc, precleaned=True, source_xref=src_xref, original_name=name)
                if r2 is not None and r2.get("bigg_metabolite"):
                    return r2
                refusal = refusal or r2
            if refusal is not None and strict:
                return refusal
            if refusal is not None:
                return None
        if strict:
            return self._refuse(name, "no candidate matched the source name in any lane",
                                source_xref=src_xref)
        return None

    def _by_name(self, name, precleaned=False, source_xref=None, original_name=None):
        """Resolve by name, chemistry first. Returns a result, a refusal, or None.

        A refusal (evidence_tier 'unmapped') means candidates existed but none could
        be chosen on the evidence. None means nothing matched at all. Lanes are tried
        in order of evidential strength; a refusal in one lane does NOT stop a later
        lane from resolving the name correctly -- it is only returned if every lane
        fails, so the refusal reason survives to the ledger.
        """
        src = original_name if original_name is not None else name
        suffix = "_salt" if precleaned else ""
        want = CHEM.stereo_of_name(name)
        first_refusal = None

        def _keep(refusal):
            nonlocal first_refusal
            if first_refusal is None:
                first_refusal = refusal
            return None

        # 0) Formula-shaped tokens resolve by CHEMISTRY, on the RAW string, before
        #    norm() destroys case and charge. This is what keeps CO2 out of cobalt.
        tok = CHEM.resolve_formula_token(name)
        if tok is not None:
            bid, why = tok
            if bid is None:
                return self._refuse(src, f"formula token refused: {why}", source_xref)
            if bid in self.dict:
                return self._result(bid, "formula_token" + suffix, "exact_name",
                                    match_key=str(name).strip(), match_field="formula_token",
                                    source_name=src, source_xref=source_xref, note=why)

        n = norm(name)
        if not n:
            return None
        strict_key = re.sub(r"[^a-z0-9]", "", (name or "").lower())
        ambiguous_key = n in CHEM.AMBIGUOUS_NORM_KEYS

        def _lane(hits, method, match_key, match_field, exact_ok=True):
            """Run one candidate set through the chemistry/stereo gate."""
            if not hits:
                return None
            bid, qual, why = self._choose(hits, want_stereo=want)
            if not bid:
                return _keep(self._refuse(src, why, source_xref))
            tier = "exact_name" if (exact_ok and qual in ("stereo_matched", "unique")) else "fuzzy_name"
            return self._result(bid, method + suffix, tier, match_key=match_key,
                                match_field=match_field, source_name=src, source_xref=source_xref)

        # 1) stereo-PRESERVING exact name index. 'lserine' -> ser__L directly, so a
        #    name that already says which enantiomer it is never reaches a blind key.
        if not ambiguous_key:
            r = _lane(self.name_strict.get(strict_key), "name_strict",
                      str(name).strip(), "bigg_name")
            if r is not None:
                return r
            # 1b) same, with BiGG's trailing molecular formula stripped:
            #     'L Ornithine C5H13N2O2' -> key 'lornithine' -> orn__L
            r = _lane(self.name_strict_nf.get(strict_key), "name_strict_deformula",
                      str(name).strip(), "bigg_name_deformula")
            if r is not None:
                return r

        # 2) stereo-blind name index, gated on the declared stereochemistry.
        if ambiguous_key:
            return self._refuse(src, "case-folded name key is chemically ambiguous: "
                                + CHEM.AMBIGUOUS_NORM_KEYS[n], source_xref)
        r = _lane(self.name_idx.get(n), "name", str(name).strip(), "bigg_name")
        if r is not None:
            return r

        # 3) alias table. Keyed on the stereo-STRIPPED form (that is what makes
        #    "L-Glutamic acid" -> glu__L work), so the alias target must still be
        #    checked against the stereochemistry the source declared.
        if n in self.aliases:
            bid = self.aliases[n]
            tgt_stereo = CHEM.stereo_of_id(bid)
            if want in ("L", "D") and tgt_stereo and tgt_stereo != want:
                sib = f"{CHEM.id_stereo_base(bid)}__{want}"
                if sib in self.dict:
                    return self._result(sib, "name_alias" + suffix, "fuzzy_name",
                                        match_key=n, match_field="alias_table",
                                        source_name=src, source_xref=source_xref,
                                        note=f"alias target {bid} corrected to {sib} on the "
                                             f"{want}- descriptor the source declared")
                return self._refuse(src, f"source declares {want}- but the alias table "
                                         f"target is {bid} and no {want}- sibling exists",
                                    source_xref)
            if want == "DL" and tgt_stereo:
                return self._refuse(src, f"source declares DL (racemate); alias target "
                                         f"{bid} is a single enantiomer", source_xref)
            return self._result(bid, "name_alias" + suffix, "fuzzy_name",
                                match_key=n, match_field="alias_table",
                                source_name=src, source_xref=source_xref)

        # 4) BiGG name with the trailing molecular formula stripped (stereo-blind key)
        r = _lane(self.name_nf.get(n), "name_deformula", str(name).strip(),
                  "bigg_name_deformula", exact_ok=False)
        if r is not None:
            return r

        # 5) data-driven acid heuristic: "...ic acid" -> "...ate" / "...oate"
        m2 = re.match(r"(.+?)ic(?:acid)?$", n)
        if m2:
            stem = m2.group(1)
            for cand in (stem + "ate", stem + "oate"):
                r = _lane(self.name_idx.get(cand), "name_acid_heuristic", cand,
                          "acid_heuristic", exact_ok=False)
                if r is not None:
                    return r
        return first_refusal


if __name__ == "__main__":
    m = Mapper()
    for kw in [dict(name="D-Glucose"), dict(inchikey="WQZGKKKJIJFFOK-GASJEMHNSA-N"),
               dict(kegg="C00031"), dict(hmdb="HMDB0000122"), dict(name="L-Tryptophan"),
               dict(chebi="CHEBI:16810"), dict(name="not-a-real-metabolite"),
               dict(name="CO2"), dict(name="Co2+"), dict(name="L-Serine"), dict(name="D-Serine")]:
        r = m.map(**kw)
        if r is None:
            print(kw, "-> None")
        else:
            print(kw, "->", r["bigg_metabolite"], "|", r["evidence_tier"], "| match_key=",
                  r.get("match_key"), "|", r.get("mapping_note", ""))
